#!/usr/bin/sh

clear
echo "Build started."

#export CC=/usr/bin/clang
#export CXX=/usr/bin/clang++

if [ ! -d "builds" ]; then
    echo "Configuring CMake..."
	mkdir -p "builds"
	mkdir -p "builds/linux"
	cd "builds/linux"
	cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug ../../
elif [ ! -d "builds/linux" ]; then
	echo "Configuring CMake.."
    mkdir -p "builds/linux"
	cd "builds/linux"
	cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug ../../
else
	cd "builds/linux"
fi

echo "Building..."
cmake --build ./
cp "compile_commands.json" ../../
echo "Build finished."
